services:
  ibs-care-api:
    image: ghcr.io/limogiai/ibs-care-api:latest
    ports:
      - "4433:4433"
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: always